package:
  name: eccodes
  version: 2.30.0

build:
  number: 0
source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.30.0-Source.tar.gz
#  git_rev: {{ version }}
  
requirements:
  build:
    - cmake
