package:
  name: eccodes
  version: 2.33.0

build:
  number: 0
source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.33.0-Source.tar.gz
#   url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.37.0-Source.tar.gz?api=v2
#  git_rev: {{ version }}
  
requirements:
  build:
    - cmake

  host:  
    - libaec 1.1.2
