[tool.towncrier]
directory = "product/runtime/docs/sphinx/changes"
filename = "product/runtime/docs/sphinx/changelog.rst"
issue_format = "`#{issue} <https://github.com/chaquo/chaquopy/issues/{issue}>`__"
wrap = true

# Roughly in order of importance, but put the good news at the top.
type = [
    { directory = "feature", name = "Features", showcontent = true },
    { directory = "removal", name = "Deprecations and Removals", showcontent = true },
    { directory = "bugfix", name = "Bugfixes", showcontent = true },
]