package:
  name: chaquopy-freetype
  version: "2.9.1"

build:
  number: 2

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.9.1.tar.gz

about:
  license_file: docs/FTL.TXT
