{% set version = "1.3.7" %}

package:
  name: chaquopy-libvorbis
  version: {{ version }}

build:
  number: 1

source:
  url: https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-{{ version }}.tar.gz

requirements:
  host:
    - chaquopy-libogg 1.3.4
