{% set version = "1.3.3" %}

package:
  name: chaquopy-flac
  version: {{ version }}

build:
  number: 1

source:
  url: https://ftp.osuosl.org/pub/xiph/releases/flac/flac-{{ version }}.tar.xz

requirements:
  host:
    - chaquopy-libogg 1.3.4
