# pycryptodome and pycryptodomex are identical except for the name of their top-level package.
# Any change to one should also be done to the other.
package:
  name: pycryptodome
  version: "3.9.4"

build:
  number: 1
