{% set version = "2.5.0" %}

{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% else %}
    {% set numpy_version = "1.23.3" %}
{% endif %}

package:
  name: tflite-runtime
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz

requirements:
  build:
    - pybind11 2.4.3
  host:
    - python
    - numpy {{ numpy_version }}
