package:
  name: pyzmq
  # When updating, check buildutils/bundle.py and consider updating chaquopy-libzmq to
  # the matching version.
  version: "24.0.1"

build:
  number: 1

requirements:
  build:
    - packaging 22.0
  host:
    - chaquopy-libzmq 4.3.4
