package:
  name: python_example
  version: "0.0.1"

source:
  git_url: https://github.com/pybind/python_example.git
  git_rev: 2c99526baaab1c5bdac3462399437f1df3545c7d

requirements:
  build:
    - pybind11 2.6.0
  host:
    - python
