package:
  name: chaquopy-openblas
  version: "0.2.20"

source:
  url: https://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz

build:
  number: 5

requirements:
  build:
    - fortran
  host:
    - chaquopy-libgfortran 4.9
