# This is a pure-Python package, but we build it into a set of identical native-tagged wheels
# to add a requirement for the native library which it uses.

{% set version = "0.1.9" %}

package:
  name: pyzbar
  version: {{ version }}

source:
  url: https://github.com/NaturalHistoryMuseum/pyzbar/archive/v{{ version }}.tar.gz

requirements:
  host:
    - python
    - chaquopy-zbar 0.23.90
