{% set version = "1.0.28" %}

package:
  name: chaquopy-libsndfile
  version: {{ version }}

build:
  number: 1

source:
  url: http://www.mega-nerd.com/libsndfile/files/libsndfile-{{ version }}.tar.gz

requirements:
  host:
    - chaquopy-flac 1.3.3
    - chaquopy-libogg 1.3.4
    - chaquopy-libvorbis 1.3.7
